import { FontAwesomeIcon, FontAwesomeIconProps } from '@fortawesome/react-fontawesome';
import {
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBarsProgress,
  faBars,
  faCodeBranch,
  faClock,
  faCopy,
  faChevronDown,
  faChevronUp,
  faCheck,
  faCircle,
  faComment,
  faChevronRight,
  faCircleNodes,
  faCirclePlus,
  faCompress,
  faDownload,
  faEllipsis,
  faExpand,
  faFloppyDisk,
  faFile,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileExcel,
  faFileImage,
  faFileLines,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faFolder,
  faFolderOpen,
  faGear,
  faGlobe,
  faImage,
  faLink,
  faMagnifyingGlass,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMicrophone,
  faPaperclip,
  faPenToSquare,
  faPlus,
  faPuzzlePiece,
  faRotateLeft,
  faSquarePlus,
  faSliders,
  faStop,
  faTableColumns,
  faTerminal,
  faThumbtack,
  faTrashCan,
  faTriangleExclamation,
  faComments,
  faCode,
  faXmark,
  faWindowMinimize,
  faWindowMaximize,
  faWindowRestore,
  faCodeMerge,
  faCodeCommit,
  faTag,
  faDiagramProject,
} from '@fortawesome/free-solid-svg-icons';

export { FontAwesomeIcon };
export type UiIconProps = Omit<FontAwesomeIconProps, 'icon'> & { icon: typeof faPlus };

export const icons = {
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  menu: faBars,
  external: faArrowUpRightFromSquare,
  refresh: faArrowsRotate,
  activity: faBarsProgress,
  branch: faCodeBranch,
  clock: faClock,
  compress: faCompress,
  copy: faCopy,
  expand: faExpand,
  down: faChevronDown,
  up: faChevronUp,
  check: faCheck,
  warning: faTriangleExclamation,
  circle: faCircle,
  comment: faComment,
  right: faChevronRight,
  nodes: faCircleNodes,
  circlePlus: faCirclePlus,
  download: faDownload,
  save: faFloppyDisk,
  file: faFile,
  fileArchive: faFileArchive,
  fileAudio: faFileAudio,
  fileCode: faFileCode,
  fileExcel: faFileExcel,
  fileImage: faFileImage,
  fileLines: faFileLines,
  filePdf: faFilePdf,
  filePowerpoint: faFilePowerpoint,
  fileVideo: faFileVideo,
  fileWord: faFileWord,
  folder: faFolder,
  folderOpen: faFolderOpen,
  gear: faGear,
  globe: faGlobe,
  image: faImage,
  link: faLink,
  search: faMagnifyingGlass,
  zoomOut: faMagnifyingGlassMinus,
  zoomIn: faMagnifyingGlassPlus,
  microphone: faMicrophone,
  paperclip: faPaperclip,
  compose: faPenToSquare,
  plus: faPlus,
  puzzle: faPuzzlePiece,
  undo: faRotateLeft,
  squarePlus: faSquarePlus,
  topPanel: faSliders,
  bottomPanel: faWindowMaximize,
  sidePanel: faTableColumns,
  stop: faStop,
  terminal: faTerminal,
  pin: faThumbtack,
  trash: faTrashCan,
  comments: faComments,
  code: faCode,
  close: faXmark,
  windowMinimize: faWindowMinimize,
  windowMaximize: faWindowMaximize,
  windowRestore: faWindowRestore,
  more: faEllipsis,
  merge: faCodeMerge,
  commit: faCodeCommit,
  tag: faTag,
  graph: faDiagramProject,
} as const;

export function UiIcon({ icon, ...props }: UiIconProps) {
  return <FontAwesomeIcon icon={icon} aria-hidden="true" {...props} />;
}
